// style-dictionary.config.mjs
// Style Dictionary v4 — NOX Design System
// W3C DTCG tokens → CSS, JS/TS, Kotlin, Flutter/Dart, Android XML, Rust, C++, Python

import StyleDictionary from 'style-dictionary';

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

const toARGB      = (hex) => `0xFF${hex.replace('#', '').toUpperCase()}`;
const toHexInt    = (hex) => `0x${hex.replace('#', '').toUpperCase()}`;
const toCamel     = (path) => path.map((p, i) => i === 0 ? p : p[0].toUpperCase() + p.slice(1)).join('');
const toPascal    = (path) => path.map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const toUpperSnake= (path) => path.join('_').toUpperCase();

// ─────────────────────────────────────────────────────────────────────────────
// VALUE RESOLVERS — read token.$value + token.$type (DTCG)
// ─────────────────────────────────────────────────────────────────────────────

function resolveKotlin(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'color':      return `Color(${toARGB(v)})`;
    case 'dimension':
      return (token.path[0] === 'font' && token.path[1] === 'size') ? `${v}.sp` : `${v}.dp`;
    case 'fontWeight': return `${v}`;
    case 'number':     return `${v}f`;
    default:           return `"${v}"`;
  }
}

function resolveDart(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'color':      return { type: 'Color',  value: `Color(${toARGB(v)})` };
    case 'dimension':  return { type: 'double', value: `${v}` };
    case 'fontWeight': return { type: 'int',    value: `${v}` };
    case 'number':     return { type: 'double', value: `${v}` };
    default:           return { type: 'String', value: `'${v}'` };
  }
}

function resolveRust(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'color':      return { type: 'u32',              value: toHexInt(v) };
    case 'dimension':
    case 'number':     return { type: 'f32',              value: `${v}_f32` };
    case 'fontWeight': return { type: 'u32',              value: `${v}` };
    default:           return { type: '&\'static str',    value: `"${v}"` };
  }
}

function resolveCpp(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'color':      return { type: 'constexpr uint32_t',         value: toHexInt(v) };
    case 'dimension':
    case 'number':     return { type: 'constexpr float',            value: `${v}f` };
    case 'fontWeight': return { type: 'constexpr int',              value: `${v}` };
    default:           return { type: 'constexpr std::string_view', value: `"${v}"` };
  }
}

function resolvePython(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'color':                      return `"${v}"`;
    case 'dimension':
    case 'number':
    case 'fontWeight':                 return `${v}`;
    default:                           return `"${v}"`;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// CUSTOM FORMATS
// ─────────────────────────────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'kotlin/object',
  format: ({ dictionary }) => [
    '// NOX Design System — Kotlin / Jetpack Compose',
    '// Auto-generated by Style Dictionary. DO NOT EDIT.',
    '',
    'package nox.designsystem',
    '',
    'import androidx.compose.ui.graphics.Color',
    'import androidx.compose.ui.unit.dp',
    'import androidx.compose.ui.unit.sp',
    '',
    'object NoxTokens {',
    ...dictionary.allTokens.map((t) => {
      const comment = t.$description ? `  // ${t.$description}` : '';
      return `  val ${toPascal(t.path)} = ${resolveKotlin(t)}${comment}`;
    }),
    '}',
    '',
  ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'flutter/dart',
  format: ({ dictionary }) => [
    '// NOX Design System — Flutter / Dart',
    '// Auto-generated by Style Dictionary. DO NOT EDIT.',
    '',
    "import 'package:flutter/material.dart';",
    '',
    'class NoxTokens {',
    '  NoxTokens._();',
    '',
    ...dictionary.allTokens.map((t) => {
      const { type, value } = resolveDart(t);
      const comment = t.$description ? `  // ${t.$description}\n` : '';
      // Note: no nested 'const' — 'static const' is enough in Dart
      return `${comment}  static const ${type} ${toCamel(t.path)} = ${value};`;
    }),
    '}',
    '',
  ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'rust/constants',
  format: ({ dictionary }) => [
    '// NOX Design System — Rust',
    '// Auto-generated by Style Dictionary. DO NOT EDIT.',
    '',
    '#![allow(dead_code)]',
    '',
    'pub mod nox_tokens {',
    ...dictionary.allTokens.map((t) => {
      const { type, value } = resolveRust(t);
      const comment = t.$description ? `  /// ${t.$description}\n` : '';
      return `${comment}  pub const ${toUpperSnake(t.path)}: ${type} = ${value};`;
    }),
    '}',
    '',
  ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'cpp/header',
  format: ({ dictionary }) => [
    '// NOX Design System — C++',
    '// Auto-generated by Style Dictionary. DO NOT EDIT.',
    '',
    '#pragma once',
    '#include <cstdint>',
    '#include <string_view>',
    '',
    'namespace nox_tokens {',
    ...dictionary.allTokens.map((t) => {
      const { type, value } = resolveCpp(t);
      const comment = t.$description ? `  // ${t.$description}\n` : '';
      return `${comment}  ${type} ${toUpperSnake(t.path)} = ${value};`;
    }),
    '} // namespace nox_tokens',
    '',
  ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'python/constants',
  format: ({ dictionary }) => [
    '# NOX Design System — Python',
    '# Auto-generated by Style Dictionary. DO NOT EDIT.',
    '',
    'class NoxTokens:',
    ...dictionary.allTokens.map((t) => {
      const comment = t.$description ? `    # ${t.$description}\n` : '';
      return `${comment}    ${toUpperSnake(t.path)} = ${resolvePython(t)}`;
    }),
    '',
  ].join('\n'),
});

// ─────────────────────────────────────────────────────────────────────────────
// CUSTOM TRANSFORMS
// ─────────────────────────────────────────────────────────────────────────────

// dimension/px — raw value + "px" (no rem conversion). Used by CSS and JS.
StyleDictionary.registerTransform({
  name: 'dimension/px',
  type: 'value',
  filter: (token) => token.$type === 'dimension',
  transform: (token) => {
    const v = token.$value;
    return v === '0' || v === 0 ? '0' : `${v}px`;
  },
});

// dimension/dp — raw value + "dp" (no rem conversion). Used by Android XML.
StyleDictionary.registerTransform({
  name: 'dimension/dp',
  type: 'value',
  filter: (token) => token.$type === 'dimension',
  transform: (token) => {
    const v = token.$value;
    return v === '0' || v === 0 ? '0dp' : `${v}dp`;
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// CUSTOM TRANSFORM GROUPS
// Replace sizeRem with our px/dp transforms so values are never ×16
// ─────────────────────────────────────────────────────────────────────────────

// css-nox: standard CSS group minus sizeRem, plus dimension/px
StyleDictionary.registerTransformGroup({
  name: 'css-nox',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'time/seconds',
    'html/icon',
    'dimension/px',      // <-- replaces sizeRem
    'color/css',
    'asset/url',
    'fontFamily/css',
    'cubicBezier/css',
    'strokeStyle/css/shorthand',
    'border/css/shorthand',
    'typography/css/shorthand',
    'transition/css/shorthand',
    'shadow/css/shorthand',
  ],
});

// js-nox: standard JS group minus sizeRem, plus dimension/px
StyleDictionary.registerTransformGroup({
  name: 'js-nox',
  transforms: [
    'attribute/cti',
    'name/pascal',
    'dimension/px',      // <-- replaces sizeRem
    'color/hex',
  ],
});

// android-nox: standard android group minus sizeRemToDp/sizeRemToSp, plus dimension/dp
StyleDictionary.registerTransformGroup({
  name: 'android-nox',
  transforms: [
    'attribute/cti',
    'name/snake',
    'color/hex8android',
    'dimension/dp',      // <-- replaces sizeRemToDp + sizeRemToSp
  ],
});

// ─────────────────────────────────────────────────────────────────────────────
// MAIN CONFIG
// ─────────────────────────────────────────────────────────────────────────────

const sd = new StyleDictionary({
  log: { verbosity: 'verbose' },
  usesDtcg: true,
  source: ['tokens/**/*.json'],

  platforms: {

    css: {
      transformGroup: 'css-nox',
      prefix: 'nox',
      buildPath: 'dist/css/',
      files: [{
        destination: 'nox-tokens.css',
        format: 'css/variables',
        options: { outputReferences: false },
      }],
    },

    js: {
      transformGroup: 'js-nox',
      buildPath: 'dist/js/',
      files: [{
        destination: 'nox-tokens.mjs',
        format: 'javascript/es6',
      }],
    },

    ts: {
      transformGroup: 'js-nox',
      buildPath: 'dist/ts/',
      files: [{
        destination: 'nox-tokens.d.ts',
        format: 'typescript/es6-declarations',
      }],
    },

    'android-xml': {
      transformGroup: 'android-nox',
      buildPath: 'dist/android/',
      files: [
        {
          destination: 'nox_colors.xml',
          format: 'android/colors',
          filter: (t) => t.$type === 'color',
        },
        {
          destination: 'nox_dimens.xml',
          format: 'android/resources',
          filter: (t) => t.$type === 'dimension',
          options: { resourceType: 'dimen' },
        },
      ],
    },

    // Custom platforms: name/kebab only — values read directly via token.$value
    kotlin: {
      transforms: ['name/kebab'],
      buildPath: 'dist/kotlin/',
      files: [{
        destination: 'NoxTokens.kt',
        format: 'kotlin/object',
      }],
    },

    flutter: {
      transforms: ['name/kebab'],
      buildPath: 'dist/flutter/',
      files: [{
        destination: 'nox_tokens.dart',
        format: 'flutter/dart',
      }],
    },

    rust: {
      transforms: ['name/kebab'],
      buildPath: 'dist/rust/',
      files: [{
        destination: 'nox_tokens.rs',
        format: 'rust/constants',
      }],
    },

    cpp: {
      transforms: ['name/kebab'],
      buildPath: 'dist/cpp/',
      files: [{
        destination: 'nox_tokens.hpp',
        format: 'cpp/header',
      }],
    },

    python: {
      transforms: ['name/kebab'],
      buildPath: 'dist/python/',
      files: [{
        destination: 'nox_tokens.py',
        format: 'python/constants',
      }],
    },
  },
});

await sd.buildAllPlatforms();
